---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: Flag-config-banner-test
flagType: boolean
description: banner-test
labels:

availableValues:
  - true
  - false

isPermanent: false
